version: 2.1
orbs:
    apex: circleci/salesforce-apex@1.0.1
jobs:
    auth-install:
      docker:
      # Has node-js pre-installed and allows us to install Node version of Salesforce CLI without needing to install Node and npm
        - image: cimg/node:14.5
      steps:
        # Fetches source code from the repository (typically first step)
        - checkout
        # Orb command supplied by apex orb (installs latest stand-alone version of CLI)
        - apex/setup:
           defaultusername: raymond.nguyen@brave-badger-sf5hrf.com
        - run:
            name: Run your SFDX commands here
            command: sfdx force:auth:list 
        - run:
            name: Printing some stuff
            command: echo "Hello World hehe XD"
  # Runs jobs in a particular order 
workflows:
    basic-test:
      jobs:
        - auth-install